######################################################################
# Automatically generated by qmake (2.01a) ?? 7? 5 10:05:50 2023
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += changevalue.cpp
