######################################################################
# Automatically generated by qmake (2.01a) ?? 6? 24 14:52:52 2023
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += first.cpp
