######################################################################
# Automatically generated by qmake (2.01a) ?? 6? 29 15:03:37 2023
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += first.cpp
