######################################################################
# Automatically generated by qmake (2.01a) ?? 7? 5 10:27:05 2023
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += adder1.cpp
