######################################################################
# Automatically generated by qmake (2.01a) ?? 7? 6 10:33:10 2023
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += qq.h
SOURCES += main.cpp qq.cpp
