######################################################################
# Automatically generated by qmake (2.01a) ?? 6? 30 16:17:54 2023
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += closelab2.cpp
