######################################################################
# Automatically generated by qmake (2.01a) ?? 7? 5 16:27:24 2023
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += adder.h
SOURCES += adder.cpp main.cpp
