######################################################################
# Automatically generated by qmake (2.01a) ?? 6? 30 15:52:00 2023
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += closelab.cpp
