######################################################################
# Automatically generated by qmake (2.01a) ?? 7? 4 13:36:27 2023
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += changevalue.cpp
