######################################################################
# Automatically generated by qmake (2.01a) ?? 7? 13 16:09:47 2023
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += adder.h jfq.h
SOURCES += adder.cpp main.cpp
