######################################################################
# Automatically generated by qmake (2.01a) ?? 8? 6 19:22:02 2023
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += yaojiang.h
FORMS += yaojiang.ui
SOURCES += main.cpp yaojiang.cpp
RESOURCES += \
    pics.qrc
