######################################################################
# Automatically generated by qmake (2.01a) ?? 7? 6 14:14:14 2023
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mytime.h
SOURCES += mytime.cpp
